version: "3.8"
services:
  ngrok:
    image: ngrok/ngrok:latest
    container_name: ngrok
    environment:
      - NGROK_CONFIG=/home/ngrok/.ngrok2/ngrok.yml
    volumes:
      - type: bind
        source: ./ngrok.yml
        target: /home/ngrok/.ngrok2/ngrok.yml
